export const FETCHING_COUNTRIES = 'FETCHING_COUNTRIES';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';

export const ENDPOINT = 'http://localhost:4000/';